
'------------------------------------------------------------------------------
' <auto-generated>
'    此代码是根据模板生成的。
'
'    手动更改此文件可能会导致应用程序中发生异常行为。
'    如果重新生成代码，则将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("abdb5640-8a2e-4750-9506-eeb7e38104b2")>
#Region "EDM 关系源元数据"
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_Order_Store", "Store", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Store), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order), True)>
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_Order_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(User), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order), True)>
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_Store_Trade", "Trade", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Trade), "Store", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Store), True)>
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_User_CardIssue", "CardIssue", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(CardIssue), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(User), True)>
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_Store_Salesman", "Salesman", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Salesman), "Store", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Store), True)>
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_CashOrder_Store", "Store", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Store), "CashOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(CashOrder), True)>
<Assembly: EdmRelationshipAttribute("VIPCardModel", "FK_CashOrder_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(User), "CashOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(CashOrder), True)>

#End Region

#Region "上下文"

''' <summary>
''' 没有元数据文档可用。
''' </summary>
Public Partial Class VIPCardEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' 请使用应用程序配置文件的“VIPCardEntities”部分中的连接字符串初始化新 VIPCardEntities 对象。
    ''' </summary>
    Public Sub New()
        MyBase.New("name=VIPCardEntities", "VIPCardEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' 初始化新的 VIPCardEntities 对象。
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "VIPCardEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' 初始化新的 VIPCardEntities 对象。
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "VIPCardEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet 属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Admins() As ObjectSet(Of Admin)
        Get
            If (_Admins Is Nothing) Then
                _Admins = MyBase.CreateObjectSet(Of Admin)("Admins")
            End If
            Return _Admins
        End Get
    End Property

    Private _Admins As ObjectSet(Of Admin)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property CardIssues() As ObjectSet(Of CardIssue)
        Get
            If (_CardIssues Is Nothing) Then
                _CardIssues = MyBase.CreateObjectSet(Of CardIssue)("CardIssues")
            End If
            Return _CardIssues
        End Get
    End Property

    Private _CardIssues As ObjectSet(Of CardIssue)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Orders() As ObjectSet(Of Order)
        Get
            If (_Orders Is Nothing) Then
                _Orders = MyBase.CreateObjectSet(Of Order)("Orders")
            End If
            Return _Orders
        End Get
    End Property

    Private _Orders As ObjectSet(Of Order)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Stores() As ObjectSet(Of Store)
        Get
            If (_Stores Is Nothing) Then
                _Stores = MyBase.CreateObjectSet(Of Store)("Stores")
            End If
            Return _Stores
        End Get
    End Property

    Private _Stores As ObjectSet(Of Store)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Trades() As ObjectSet(Of Trade)
        Get
            If (_Trades Is Nothing) Then
                _Trades = MyBase.CreateObjectSet(Of Trade)("Trades")
            End If
            Return _Trades
        End Get
    End Property

    Private _Trades As ObjectSet(Of Trade)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Users() As ObjectSet(Of User)
        Get
            If (_Users Is Nothing) Then
                _Users = MyBase.CreateObjectSet(Of User)("Users")
            End If
            Return _Users
        End Get
    End Property

    Private _Users As ObjectSet(Of User)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Salesman() As ObjectSet(Of Salesman)
        Get
            If (_Salesman Is Nothing) Then
                _Salesman = MyBase.CreateObjectSet(Of Salesman)("Salesman")
            End If
            Return _Salesman
        End Get
    End Property

    Private _Salesman As ObjectSet(Of Salesman)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property CashOrders() As ObjectSet(Of CashOrder)
        Get
            If (_CashOrders Is Nothing) Then
                _CashOrders = MyBase.CreateObjectSet(Of CashOrder)("CashOrders")
            End If
            Return _CashOrders
        End Get
    End Property

    Private _CashOrders As ObjectSet(Of CashOrder)

    #End Region
    #Region "AddTo 方法"

    ''' <summary>
    ''' 用于向 Admins EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToAdmins(ByVal admin As Admin)
        MyBase.AddObject("Admins", admin)
    End Sub

    ''' <summary>
    ''' 用于向 CardIssues EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToCardIssues(ByVal cardIssue As CardIssue)
        MyBase.AddObject("CardIssues", cardIssue)
    End Sub

    ''' <summary>
    ''' 用于向 Orders EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToOrders(ByVal order As Order)
        MyBase.AddObject("Orders", order)
    End Sub

    ''' <summary>
    ''' 用于向 Stores EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToStores(ByVal store As Store)
        MyBase.AddObject("Stores", store)
    End Sub

    ''' <summary>
    ''' 用于向 Trades EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToTrades(ByVal trade As Trade)
        MyBase.AddObject("Trades", trade)
    End Sub

    ''' <summary>
    ''' 用于向 Users EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub

    ''' <summary>
    ''' 用于向 Salesman EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToSalesman(ByVal salesman As Salesman)
        MyBase.AddObject("Salesman", salesman)
    End Sub

    ''' <summary>
    ''' 用于向 CashOrders EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToCashOrders(ByVal cashOrder As CashOrder)
        MyBase.AddObject("CashOrders", cashOrder)
    End Sub

    #End Region
End Class

#End Region
#Region "实体"

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="Admin")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Admin
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Admin 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="用户名">用户名 属性的初始值。</param>
    ''' <param name="密码">密码 属性的初始值。</param>
    Public Shared Function CreateAdmin(编号 As Global.System.Int32, 用户名 As Global.System.String, 密码 As Global.System.String) As Admin
        Dim admin as Admin = New Admin
        admin.编号 = 编号
        admin.用户名 = 用户名
        admin.密码 = 密码
        Return admin
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 用户名() As Global.System.String
        Get
            Return _用户名
        End Get
        Set
            On用户名Changing(value)
            ReportPropertyChanging("用户名")
            _用户名 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("用户名")
            On用户名Changed()
        End Set
    End Property

    Private _用户名 As Global.System.String
    Private Partial Sub On用户名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On用户名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 密码() As Global.System.String
        Get
            Return _密码
        End Get
        Set
            On密码Changing(value)
            ReportPropertyChanging("密码")
            _密码 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("密码")
            On密码Changed()
        End Set
    End Property

    Private _密码 As Global.System.String
    Private Partial Sub On密码Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On密码Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 卡号() As Global.System.String
        Get
            Return _卡号
        End Get
        Set
            On卡号Changing(value)
            ReportPropertyChanging("卡号")
            _卡号 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("卡号")
            On卡号Changed()
        End Set
    End Property

    Private _卡号 As Global.System.String
    Private Partial Sub On卡号Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On卡号Changed()
    End Sub

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="CardIssue")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class CardIssue
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 CardIssue 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="名称">名称 属性的初始值。</param>
    Public Shared Function CreateCardIssue(编号 As Global.System.Int32, 名称 As Global.System.String) As CardIssue
        Dim cardIssue as CardIssue = New CardIssue
        cardIssue.编号 = 编号
        cardIssue.名称 = 名称
        Return cardIssue
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 名称() As Global.System.String
        Get
            Return _名称
        End Get
        Set
            On名称Changing(value)
            ReportPropertyChanging("名称")
            _名称 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("名称")
            On名称Changed()
        End Set
    End Property

    Private _名称 As Global.System.String
    Private Partial Sub On名称Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On名称Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 发卡范围() As Global.System.String
        Get
            Return _发卡范围
        End Get
        Set
            On发卡范围Changing(value)
            ReportPropertyChanging("发卡范围")
            _发卡范围 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("发卡范围")
            On发卡范围Changed()
        End Set
    End Property

    Private _发卡范围 As Global.System.String
    Private Partial Sub On发卡范围Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On发卡范围Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 卡号() As Global.System.String
        Get
            Return _卡号
        End Get
        Set
            On卡号Changing(value)
            ReportPropertyChanging("卡号")
            _卡号 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("卡号")
            On卡号Changed()
        End Set
    End Property

    Private _卡号 As Global.System.String
    Private Partial Sub On卡号Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On卡号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 密码() As Global.System.String
        Get
            Return _密码
        End Get
        Set
            On密码Changing(value)
            ReportPropertyChanging("密码")
            _密码 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("密码")
            On密码Changed()
        End Set
    End Property

    Private _密码 As Global.System.String
    Private Partial Sub On密码Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On密码Changed()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_User_CardIssue", "User")>
     Public Property User() As EntityCollection(Of User)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of User)("VIPCardModel.FK_User_CardIssue", "User")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of User)("VIPCardModel.FK_User_CardIssue", "User", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="CashOrder")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class CashOrder
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 CashOrder 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="用户ID">用户ID 属性的初始值。</param>
    ''' <param name="店铺ID">店铺ID 属性的初始值。</param>
    ''' <param name="金额">金额 属性的初始值。</param>
    ''' <param name="时间">时间 属性的初始值。</param>
    ''' <param name="成本">成本 属性的初始值。</param>
    ''' <param name="消费返还">消费返还 属性的初始值。</param>
    ''' <param name="发卡方提成">发卡方提成 属性的初始值。</param>
    ''' <param name="我方提成">我方提成 属性的初始值。</param>
    Public Shared Function CreateCashOrder(编号 As Global.System.Int32, 用户ID As Global.System.Int32, 店铺ID As Global.System.Int32, 金额 As Global.System.Decimal, 时间 As Global.System.DateTime, 成本 As Global.System.Decimal, 消费返还 As Global.System.Decimal, 发卡方提成 As Global.System.Decimal, 我方提成 As Global.System.Decimal) As CashOrder
        Dim cashOrder as CashOrder = New CashOrder
        cashOrder.编号 = 编号
        cashOrder.用户ID = 用户ID
        cashOrder.店铺ID = 店铺ID
        cashOrder.金额 = 金额
        cashOrder.时间 = 时间
        cashOrder.成本 = 成本
        cashOrder.消费返还 = 消费返还
        cashOrder.发卡方提成 = 发卡方提成
        cashOrder.我方提成 = 我方提成
        Return cashOrder
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 用户ID() As Global.System.Int32
        Get
            Return _用户ID
        End Get
        Set
            On用户IDChanging(value)
            ReportPropertyChanging("用户ID")
            _用户ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("用户ID")
            On用户IDChanged()
        End Set
    End Property

    Private _用户ID As Global.System.Int32
    Private Partial Sub On用户IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub On用户IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 店铺ID() As Global.System.Int32
        Get
            Return _店铺ID
        End Get
        Set
            On店铺IDChanging(value)
            ReportPropertyChanging("店铺ID")
            _店铺ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("店铺ID")
            On店铺IDChanged()
        End Set
    End Property

    Private _店铺ID As Global.System.Int32
    Private Partial Sub On店铺IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub On店铺IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 金额() As Global.System.Decimal
        Get
            Return _金额
        End Get
        Set
            On金额Changing(value)
            ReportPropertyChanging("金额")
            _金额 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("金额")
            On金额Changed()
        End Set
    End Property

    Private _金额 As Global.System.Decimal
    Private Partial Sub On金额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On金额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 时间() As Global.System.DateTime
        Get
            Return _时间
        End Get
        Set
            On时间Changing(value)
            ReportPropertyChanging("时间")
            _时间 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("时间")
            On时间Changed()
        End Set
    End Property

    Private _时间 As Global.System.DateTime
    Private Partial Sub On时间Changing(value As Global.System.DateTime)
    End Sub

    Private Partial Sub On时间Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 成本() As Global.System.Decimal
        Get
            Return _成本
        End Get
        Set
            On成本Changing(value)
            ReportPropertyChanging("成本")
            _成本 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("成本")
            On成本Changed()
        End Set
    End Property

    Private _成本 As Global.System.Decimal
    Private Partial Sub On成本Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On成本Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 消费返还() As Global.System.Decimal
        Get
            Return _消费返还
        End Get
        Set
            On消费返还Changing(value)
            ReportPropertyChanging("消费返还")
            _消费返还 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("消费返还")
            On消费返还Changed()
        End Set
    End Property

    Private _消费返还 As Global.System.Decimal
    Private Partial Sub On消费返还Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On消费返还Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 发卡方提成() As Global.System.Decimal
        Get
            Return _发卡方提成
        End Get
        Set
            On发卡方提成Changing(value)
            ReportPropertyChanging("发卡方提成")
            _发卡方提成 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("发卡方提成")
            On发卡方提成Changed()
        End Set
    End Property

    Private _发卡方提成 As Global.System.Decimal
    Private Partial Sub On发卡方提成Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On发卡方提成Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 我方提成() As Global.System.Decimal
        Get
            Return _我方提成
        End Get
        Set
            On我方提成Changing(value)
            ReportPropertyChanging("我方提成")
            _我方提成 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("我方提成")
            On我方提成Changed()
        End Set
    End Property

    Private _我方提成 As Global.System.Decimal
    Private Partial Sub On我方提成Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On我方提成Changed()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_CashOrder_Store", "Store")>
    Public Property Store() As Store
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Store)("VIPCardModel.FK_CashOrder_Store", "Store").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Store)("VIPCardModel.FK_CashOrder_Store", "Store").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property StoreReference() As EntityReference(Of Store)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Store)("VIPCardModel.FK_CashOrder_Store", "Store")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Store)("VIPCardModel.FK_CashOrder_Store", "Store", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_CashOrder_User", "User")>
    Public Property User() As User
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("VIPCardModel.FK_CashOrder_User", "User").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("VIPCardModel.FK_CashOrder_User", "User").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property UserReference() As EntityReference(Of User)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("VIPCardModel.FK_CashOrder_User", "User")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("VIPCardModel.FK_CashOrder_User", "User", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="Order")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Order
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Order 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="用户ID">用户ID 属性的初始值。</param>
    ''' <param name="店铺ID">店铺ID 属性的初始值。</param>
    ''' <param name="金额">金额 属性的初始值。</param>
    ''' <param name="时间">时间 属性的初始值。</param>
    ''' <param name="成本">成本 属性的初始值。</param>
    ''' <param name="消费返还">消费返还 属性的初始值。</param>
    ''' <param name="发卡方提成">发卡方提成 属性的初始值。</param>
    ''' <param name="我方提成">我方提成 属性的初始值。</param>
    Public Shared Function CreateOrder(编号 As Global.System.Int32, 用户ID As Global.System.Int32, 店铺ID As Global.System.Int32, 金额 As Global.System.Decimal, 时间 As Global.System.DateTime, 成本 As Global.System.Decimal, 消费返还 As Global.System.Decimal, 发卡方提成 As Global.System.Decimal, 我方提成 As Global.System.Decimal) As Order
        Dim order as Order = New Order
        order.编号 = 编号
        order.用户ID = 用户ID
        order.店铺ID = 店铺ID
        order.金额 = 金额
        order.时间 = 时间
        order.成本 = 成本
        order.消费返还 = 消费返还
        order.发卡方提成 = 发卡方提成
        order.我方提成 = 我方提成
        Return order
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 用户ID() As Global.System.Int32
        Get
            Return _用户ID
        End Get
        Set
            On用户IDChanging(value)
            ReportPropertyChanging("用户ID")
            _用户ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("用户ID")
            On用户IDChanged()
        End Set
    End Property

    Private _用户ID As Global.System.Int32
    Private Partial Sub On用户IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub On用户IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 店铺ID() As Global.System.Int32
        Get
            Return _店铺ID
        End Get
        Set
            On店铺IDChanging(value)
            ReportPropertyChanging("店铺ID")
            _店铺ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("店铺ID")
            On店铺IDChanged()
        End Set
    End Property

    Private _店铺ID As Global.System.Int32
    Private Partial Sub On店铺IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub On店铺IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 金额() As Global.System.Decimal
        Get
            Return _金额
        End Get
        Set
            On金额Changing(value)
            ReportPropertyChanging("金额")
            _金额 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("金额")
            On金额Changed()
        End Set
    End Property

    Private _金额 As Global.System.Decimal
    Private Partial Sub On金额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On金额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 时间() As Global.System.DateTime
        Get
            Return _时间
        End Get
        Set
            On时间Changing(value)
            ReportPropertyChanging("时间")
            _时间 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("时间")
            On时间Changed()
        End Set
    End Property

    Private _时间 As Global.System.DateTime
    Private Partial Sub On时间Changing(value As Global.System.DateTime)
    End Sub

    Private Partial Sub On时间Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 成本() As Global.System.Decimal
        Get
            Return _成本
        End Get
        Set
            On成本Changing(value)
            ReportPropertyChanging("成本")
            _成本 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("成本")
            On成本Changed()
        End Set
    End Property

    Private _成本 As Global.System.Decimal
    Private Partial Sub On成本Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On成本Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 消费返还() As Global.System.Decimal
        Get
            Return _消费返还
        End Get
        Set
            On消费返还Changing(value)
            ReportPropertyChanging("消费返还")
            _消费返还 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("消费返还")
            On消费返还Changed()
        End Set
    End Property

    Private _消费返还 As Global.System.Decimal
    Private Partial Sub On消费返还Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On消费返还Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 发卡方提成() As Global.System.Decimal
        Get
            Return _发卡方提成
        End Get
        Set
            On发卡方提成Changing(value)
            ReportPropertyChanging("发卡方提成")
            _发卡方提成 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("发卡方提成")
            On发卡方提成Changed()
        End Set
    End Property

    Private _发卡方提成 As Global.System.Decimal
    Private Partial Sub On发卡方提成Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On发卡方提成Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 我方提成() As Global.System.Decimal
        Get
            Return _我方提成
        End Get
        Set
            On我方提成Changing(value)
            ReportPropertyChanging("我方提成")
            _我方提成 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("我方提成")
            On我方提成Changed()
        End Set
    End Property

    Private _我方提成 As Global.System.Decimal
    Private Partial Sub On我方提成Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On我方提成Changed()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Order_Store", "Store")>
    Public Property Store() As Store
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Store)("VIPCardModel.FK_Order_Store", "Store").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Store)("VIPCardModel.FK_Order_Store", "Store").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property StoreReference() As EntityReference(Of Store)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Store)("VIPCardModel.FK_Order_Store", "Store")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Store)("VIPCardModel.FK_Order_Store", "Store", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Order_User", "User")>
    Public Property User() As User
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("VIPCardModel.FK_Order_User", "User").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("VIPCardModel.FK_Order_User", "User").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property UserReference() As EntityReference(Of User)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("VIPCardModel.FK_Order_User", "User")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("VIPCardModel.FK_Order_User", "User", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="Salesman")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Salesman
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Salesman 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="姓名">姓名 属性的初始值。</param>
    ''' <param name="密码">密码 属性的初始值。</param>
    Public Shared Function CreateSalesman(编号 As Global.System.Int32, 姓名 As Global.System.String, 密码 As Global.System.String) As Salesman
        Dim salesman as Salesman = New Salesman
        salesman.编号 = 编号
        salesman.姓名 = 姓名
        salesman.密码 = 密码
        Return salesman
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 姓名() As Global.System.String
        Get
            Return _姓名
        End Get
        Set
            On姓名Changing(value)
            ReportPropertyChanging("姓名")
            _姓名 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("姓名")
            On姓名Changed()
        End Set
    End Property

    Private _姓名 As Global.System.String
    Private Partial Sub On姓名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On姓名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 密码() As Global.System.String
        Get
            Return _密码
        End Get
        Set
            On密码Changing(value)
            ReportPropertyChanging("密码")
            _密码 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("密码")
            On密码Changed()
        End Set
    End Property

    Private _密码 As Global.System.String
    Private Partial Sub On密码Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On密码Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 手机() As Global.System.String
        Get
            Return _手机
        End Get
        Set
            On手机Changing(value)
            ReportPropertyChanging("手机")
            _手机 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("手机")
            On手机Changed()
        End Set
    End Property

    Private _手机 As Global.System.String
    Private Partial Sub On手机Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On手机Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 卡号() As Global.System.String
        Get
            Return _卡号
        End Get
        Set
            On卡号Changing(value)
            ReportPropertyChanging("卡号")
            _卡号 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("卡号")
            On卡号Changed()
        End Set
    End Property

    Private _卡号 As Global.System.String
    Private Partial Sub On卡号Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On卡号Changed()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Store_Salesman", "Store")>
     Public Property Store() As EntityCollection(Of Store)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Store)("VIPCardModel.FK_Store_Salesman", "Store")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Store)("VIPCardModel.FK_Store_Salesman", "Store", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="Store")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Store
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Store 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="店名">店名 属性的初始值。</param>
    ''' <param name="所属行业ID">所属行业ID 属性的初始值。</param>
    ''' <param name="客户端ID">客户端ID 属性的初始值。</param>
    Public Shared Function CreateStore(编号 As Global.System.Int32, 店名 As Global.System.String, 所属行业ID As Global.System.Int32, 客户端ID As Global.System.String) As Store
        Dim store as Store = New Store
        store.编号 = 编号
        store.店名 = 店名
        store.所属行业ID = 所属行业ID
        store.客户端ID = 客户端ID
        Return store
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 店名() As Global.System.String
        Get
            Return _店名
        End Get
        Set
            On店名Changing(value)
            ReportPropertyChanging("店名")
            _店名 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("店名")
            On店名Changed()
        End Set
    End Property

    Private _店名 As Global.System.String
    Private Partial Sub On店名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On店名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 所属行业ID() As Global.System.Int32
        Get
            Return _所属行业ID
        End Get
        Set
            On所属行业IDChanging(value)
            ReportPropertyChanging("所属行业ID")
            _所属行业ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("所属行业ID")
            On所属行业IDChanged()
        End Set
    End Property

    Private _所属行业ID As Global.System.Int32
    Private Partial Sub On所属行业IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub On所属行业IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 客户端ID() As Global.System.String
        Get
            Return _客户端ID
        End Get
        Set
            On客户端IDChanging(value)
            ReportPropertyChanging("客户端ID")
            _客户端ID = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("客户端ID")
            On客户端IDChanged()
        End Set
    End Property

    Private _客户端ID As Global.System.String
    Private Partial Sub On客户端IDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub On客户端IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 业务员ID() As Nullable(Of Global.System.Int32)
        Get
            Return _业务员ID
        End Get
        Set
            On业务员IDChanging(value)
            ReportPropertyChanging("业务员ID")
            _业务员ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("业务员ID")
            On业务员IDChanged()
        End Set
    End Property

    Private _业务员ID As Nullable(Of Global.System.Int32)
    Private Partial Sub On业务员IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub On业务员IDChanged()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Order_Store", "Order")>
     Public Property Orders() As EntityCollection(Of Order)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("VIPCardModel.FK_Order_Store", "Order")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("VIPCardModel.FK_Order_Store", "Order", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Store_Trade", "Trade")>
    Public Property Trade() As Trade
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Trade)("VIPCardModel.FK_Store_Trade", "Trade").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Trade)("VIPCardModel.FK_Store_Trade", "Trade").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property TradeReference() As EntityReference(Of Trade)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Trade)("VIPCardModel.FK_Store_Trade", "Trade")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Trade)("VIPCardModel.FK_Store_Trade", "Trade", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Store_Salesman", "Salesman")>
    Public Property Salesman() As Salesman
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Salesman)("VIPCardModel.FK_Store_Salesman", "Salesman").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Salesman)("VIPCardModel.FK_Store_Salesman", "Salesman").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SalesmanReference() As EntityReference(Of Salesman)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Salesman)("VIPCardModel.FK_Store_Salesman", "Salesman")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Salesman)("VIPCardModel.FK_Store_Salesman", "Salesman", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_CashOrder_Store", "CashOrder")>
     Public Property CashOrders() As EntityCollection(Of CashOrder)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of CashOrder)("VIPCardModel.FK_CashOrder_Store", "CashOrder")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of CashOrder)("VIPCardModel.FK_CashOrder_Store", "CashOrder", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="Trade")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Trade
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Trade 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="名称">名称 属性的初始值。</param>
    ''' <param name="发卡方分成">发卡方分成 属性的初始值。</param>
    ''' <param name="成本比重">成本比重 属性的初始值。</param>
    ''' <param name="消费方分成">消费方分成 属性的初始值。</param>
    Public Shared Function CreateTrade(编号 As Global.System.Int32, 名称 As Global.System.String, 发卡方分成 As Global.System.Int32, 成本比重 As Global.System.Int32, 消费方分成 As Global.System.Int32) As Trade
        Dim trade as Trade = New Trade
        trade.编号 = 编号
        trade.名称 = 名称
        trade.发卡方分成 = 发卡方分成
        trade.成本比重 = 成本比重
        trade.消费方分成 = 消费方分成
        Return trade
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 名称() As Global.System.String
        Get
            Return _名称
        End Get
        Set
            On名称Changing(value)
            ReportPropertyChanging("名称")
            _名称 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("名称")
            On名称Changed()
        End Set
    End Property

    Private _名称 As Global.System.String
    Private Partial Sub On名称Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On名称Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 发卡方分成() As Global.System.Int32
        Get
            Return _发卡方分成
        End Get
        Set
            On发卡方分成Changing(value)
            ReportPropertyChanging("发卡方分成")
            _发卡方分成 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("发卡方分成")
            On发卡方分成Changed()
        End Set
    End Property

    Private _发卡方分成 As Global.System.Int32
    Private Partial Sub On发卡方分成Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On发卡方分成Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 成本比重() As Global.System.Int32
        Get
            Return _成本比重
        End Get
        Set
            On成本比重Changing(value)
            ReportPropertyChanging("成本比重")
            _成本比重 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("成本比重")
            On成本比重Changed()
        End Set
    End Property

    Private _成本比重 As Global.System.Int32
    Private Partial Sub On成本比重Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On成本比重Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 消费方分成() As Global.System.Int32
        Get
            Return _消费方分成
        End Get
        Set
            On消费方分成Changing(value)
            ReportPropertyChanging("消费方分成")
            _消费方分成 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("消费方分成")
            On消费方分成Changed()
        End Set
    End Property

    Private _消费方分成 As Global.System.Int32
    Private Partial Sub On消费方分成Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On消费方分成Changed()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Store_Trade", "Store")>
     Public Property Stores() As EntityCollection(Of Store)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Store)("VIPCardModel.FK_Store_Trade", "Store")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Store)("VIPCardModel.FK_Store_Trade", "Store", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="VIPCardModel", Name:="User")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class User
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 User 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="密码">密码 属性的初始值。</param>
    ''' <param name="卡号">卡号 属性的初始值。</param>
    ''' <param name="余额">余额 属性的初始值。</param>
    Public Shared Function CreateUser(编号 As Global.System.Int32, 密码 As Global.System.String, 卡号 As Global.System.String, 余额 As Global.System.Decimal) As User
        Dim user as User = New User
        user.编号 = 编号
        user.密码 = 密码
        user.卡号 = 卡号
        user.余额 = 余额
        Return user
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 用户名() As Global.System.String
        Get
            Return _用户名
        End Get
        Set
            On用户名Changing(value)
            ReportPropertyChanging("用户名")
            _用户名 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("用户名")
            On用户名Changed()
        End Set
    End Property

    Private _用户名 As Global.System.String
    Private Partial Sub On用户名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On用户名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 密码() As Global.System.String
        Get
            Return _密码
        End Get
        Set
            On密码Changing(value)
            ReportPropertyChanging("密码")
            _密码 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("密码")
            On密码Changed()
        End Set
    End Property

    Private _密码 As Global.System.String
    Private Partial Sub On密码Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On密码Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 手机() As Global.System.String
        Get
            Return _手机
        End Get
        Set
            On手机Changing(value)
            ReportPropertyChanging("手机")
            _手机 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("手机")
            On手机Changed()
        End Set
    End Property

    Private _手机 As Global.System.String
    Private Partial Sub On手机Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On手机Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 卡号() As Global.System.String
        Get
            Return _卡号
        End Get
        Set
            On卡号Changing(value)
            ReportPropertyChanging("卡号")
            _卡号 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("卡号")
            On卡号Changed()
        End Set
    End Property

    Private _卡号 As Global.System.String
    Private Partial Sub On卡号Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On卡号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 余额() As Global.System.Decimal
        Get
            Return _余额
        End Get
        Set
            On余额Changing(value)
            ReportPropertyChanging("余额")
            _余额 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("余额")
            On余额Changed()
        End Set
    End Property

    Private _余额 As Global.System.Decimal
    Private Partial Sub On余额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On余额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 发卡方编号() As Nullable(Of Global.System.Int32)
        Get
            Return _发卡方编号
        End Get
        Set
            On发卡方编号Changing(value)
            ReportPropertyChanging("发卡方编号")
            _发卡方编号 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("发卡方编号")
            On发卡方编号Changed()
        End Set
    End Property

    Private _发卡方编号 As Nullable(Of Global.System.Int32)
    Private Partial Sub On发卡方编号Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub On发卡方编号Changed()
    End Sub

    #End Region
    #Region "导航属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_Order_User", "Order")>
     Public Property Orders() As EntityCollection(Of Order)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("VIPCardModel.FK_Order_User", "Order")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("VIPCardModel.FK_Order_User", "Order", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_User_CardIssue", "CardIssue")>
    Public Property CardIssue() As CardIssue
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of CardIssue)("VIPCardModel.FK_User_CardIssue", "CardIssue").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of CardIssue)("VIPCardModel.FK_User_CardIssue", "CardIssue").Value = value
        End Set
    End Property
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CardIssueReference() As EntityReference(Of CardIssue)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of CardIssue)("VIPCardModel.FK_User_CardIssue", "CardIssue")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of CardIssue)("VIPCardModel.FK_User_CardIssue", "CardIssue", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("VIPCardModel", "FK_CashOrder_User", "CashOrder")>
     Public Property CashOrders() As EntityCollection(Of CashOrder)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of CashOrder)("VIPCardModel.FK_CashOrder_User", "CashOrder")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of CashOrder)("VIPCardModel.FK_CashOrder_User", "CashOrder", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

