
'------------------------------------------------------------------------------
' <auto-generated>
'    此代码是根据模板生成的。
'
'    手动更改此文件可能会导致应用程序中发生异常行为。
'    如果重新生成代码，则将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("a27a5945-e6c9-4384-be8e-8bdf6705b496")>

#Region "上下文"

''' <summary>
''' 没有元数据文档可用。
''' </summary>
Public Partial Class SMSVIPCardEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' 请使用应用程序配置文件的“SMSVIPCardEntities”部分中的连接字符串初始化新 SMSVIPCardEntities 对象。
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SMSVIPCardEntities", "SMSVIPCardEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' 初始化新的 SMSVIPCardEntities 对象。
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SMSVIPCardEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' 初始化新的 SMSVIPCardEntities 对象。
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SMSVIPCardEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet 属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Admins() As ObjectSet(Of Admin)
        Get
            If (_Admins Is Nothing) Then
                _Admins = MyBase.CreateObjectSet(Of Admin)("Admins")
            End If
            Return _Admins
        End Get
    End Property

    Private _Admins As ObjectSet(Of Admin)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property Stores() As ObjectSet(Of Store)
        Get
            If (_Stores Is Nothing) Then
                _Stores = MyBase.CreateObjectSet(Of Store)("Stores")
            End If
            Return _Stores
        End Get
    End Property

    Private _Stores As ObjectSet(Of Store)

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    Public ReadOnly Property V_User() As ObjectSet(Of V_User)
        Get
            If (_V_User Is Nothing) Then
                _V_User = MyBase.CreateObjectSet(Of V_User)("V_User")
            End If
            Return _V_User
        End Get
    End Property

    Private _V_User As ObjectSet(Of V_User)

    #End Region
    #Region "AddTo 方法"

    ''' <summary>
    ''' 用于向 Admins EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToAdmins(ByVal admin As Admin)
        MyBase.AddObject("Admins", admin)
    End Sub

    ''' <summary>
    ''' 用于向 Stores EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToStores(ByVal store As Store)
        MyBase.AddObject("Stores", store)
    End Sub

    ''' <summary>
    ''' 用于向 V_User EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet(Of T) 属性的 .Add 方法。
    ''' </summary>
    Public Sub AddToV_User(ByVal v_User As V_User)
        MyBase.AddObject("V_User", v_User)
    End Sub

    #End Region
    #Region "函数导入"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    ''' <param name="sid">没有元数据文档可用。</param>
    Public Function SP_VUser(sid As Nullable(Of Global.System.Int32)) As ObjectResult(Of V_User)
        Dim sidParameter As ObjectParameter
        If (sid.HasValue)
            sidParameter = New ObjectParameter("sid", sid)
        Else
            sidParameter = New ObjectParameter("sid", GetType(Global.System.Int32))
        End If

        Return MyBase.ExecuteFunction(Of V_User)("SP_VUser", sidParameter)

    End Function
    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    ''' <param name="mergeOption"></param>
    ''' <param name="sid">没有元数据文档可用。</param>
    Public Function SP_VUser(sid As Nullable(Of Global.System.Int32), mergeOption As MergeOption) As ObjectResult(Of V_User)
        Dim sidParameter As ObjectParameter
        If (sid.HasValue)
            sidParameter = New ObjectParameter("sid", sid)
        Else
            sidParameter = New ObjectParameter("sid", GetType(Global.System.Int32))
        End If

        Return MyBase.ExecuteFunction(Of V_User)("SP_VUser", mergeOption, sidParameter)

    End Function

    #End Region
End Class

#End Region
#Region "实体"

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Admin")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Admin
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Admin 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="用户名">用户名 属性的初始值。</param>
    ''' <param name="密码">密码 属性的初始值。</param>
    Public Shared Function CreateAdmin(编号 As Global.System.Int32, 用户名 As Global.System.String, 密码 As Global.System.String) As Admin
        Dim admin as Admin = New Admin
        admin.编号 = 编号
        admin.用户名 = 用户名
        admin.密码 = 密码
        Return admin
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 用户名() As Global.System.String
        Get
            Return _用户名
        End Get
        Set
            On用户名Changing(value)
            ReportPropertyChanging("用户名")
            _用户名 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("用户名")
            On用户名Changed()
        End Set
    End Property

    Private _用户名 As Global.System.String
    Private Partial Sub On用户名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On用户名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 密码() As Global.System.String
        Get
            Return _密码
        End Get
        Set
            On密码Changing(value)
            ReportPropertyChanging("密码")
            _密码 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("密码")
            On密码Changed()
        End Set
    End Property

    Private _密码 As Global.System.String
    Private Partial Sub On密码Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On密码Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 卡号() As Global.System.String
        Get
            Return _卡号
        End Get
        Set
            On卡号Changing(value)
            ReportPropertyChanging("卡号")
            _卡号 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("卡号")
            On卡号Changed()
        End Set
    End Property

    Private _卡号 As Global.System.String
    Private Partial Sub On卡号Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On卡号Changed()
    End Sub

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Store")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Store
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 Store 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="店名">店名 属性的初始值。</param>
    ''' <param name="所属行业ID">所属行业ID 属性的初始值。</param>
    ''' <param name="客户端ID">客户端ID 属性的初始值。</param>
    Public Shared Function CreateStore(编号 As Global.System.Int32, 店名 As Global.System.String, 所属行业ID As Global.System.Int32, 客户端ID As Global.System.String) As Store
        Dim store as Store = New Store
        store.编号 = 编号
        store.店名 = 店名
        store.所属行业ID = 所属行业ID
        store.客户端ID = 客户端ID
        Return store
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 店名() As Global.System.String
        Get
            Return _店名
        End Get
        Set
            On店名Changing(value)
            ReportPropertyChanging("店名")
            _店名 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("店名")
            On店名Changed()
        End Set
    End Property

    Private _店名 As Global.System.String
    Private Partial Sub On店名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On店名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 所属行业ID() As Global.System.Int32
        Get
            Return _所属行业ID
        End Get
        Set
            On所属行业IDChanging(value)
            ReportPropertyChanging("所属行业ID")
            _所属行业ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("所属行业ID")
            On所属行业IDChanged()
        End Set
    End Property

    Private _所属行业ID As Global.System.Int32
    Private Partial Sub On所属行业IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub On所属行业IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 客户端ID() As Global.System.String
        Get
            Return _客户端ID
        End Get
        Set
            On客户端IDChanging(value)
            ReportPropertyChanging("客户端ID")
            _客户端ID = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("客户端ID")
            On客户端IDChanged()
        End Set
    End Property

    Private _客户端ID As Global.System.String
    Private Partial Sub On客户端IDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub On客户端IDChanged()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 业务员ID() As Nullable(Of Global.System.Int32)
        Get
            Return _业务员ID
        End Get
        Set
            On业务员IDChanging(value)
            ReportPropertyChanging("业务员ID")
            _业务员ID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("业务员ID")
            On业务员IDChanged()
        End Set
    End Property

    Private _业务员ID As Nullable(Of Global.System.Int32)
    Private Partial Sub On业务员IDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub On业务员IDChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' 没有元数据文档可用。
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model", Name:="V_User")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class V_User
    Inherits EntityObject
    #Region "工厂方法"

    ''' <summary>
    ''' 创建新的 V_User 对象。
    ''' </summary>
    ''' <param name="编号">编号 属性的初始值。</param>
    ''' <param name="卡号">卡号 属性的初始值。</param>
    ''' <param name="余额">余额 属性的初始值。</param>
    ''' <param name="消费额">消费额 属性的初始值。</param>
    ''' <param name="积分消费额">积分消费额 属性的初始值。</param>
    ''' <param name="现金消费额">现金消费额 属性的初始值。</param>
    ''' <param name="状态">状态 属性的初始值。</param>
    Public Shared Function CreateV_User(编号 As Global.System.Int32, 卡号 As Global.System.String, 余额 As Global.System.Decimal, 消费额 As Global.System.Decimal, 积分消费额 As Global.System.Decimal, 现金消费额 As Global.System.Decimal, 状态 As Global.System.String) As V_User
        Dim v_User as V_User = New V_User
        v_User.编号 = 编号
        v_User.卡号 = 卡号
        v_User.余额 = 余额
        v_User.消费额 = 消费额
        v_User.积分消费额 = 积分消费额
        v_User.现金消费额 = 现金消费额
        v_User.状态 = 状态
        Return v_User
    End Function

    #End Region
    #Region "基元属性"

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 编号() As Global.System.Int32
        Get
            Return _编号
        End Get
        Set
            If (_编号 <> Value) Then
                On编号Changing(value)
                ReportPropertyChanging("编号")
                _编号 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("编号")
                On编号Changed()
            End If
        End Set
    End Property

    Private _编号 As Global.System.Int32
    Private Partial Sub On编号Changing(value As Global.System.Int32)
    End Sub

    Private Partial Sub On编号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 用户名() As Global.System.String
        Get
            Return _用户名
        End Get
        Set
            On用户名Changing(value)
            ReportPropertyChanging("用户名")
            _用户名 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("用户名")
            On用户名Changed()
        End Set
    End Property

    Private _用户名 As Global.System.String
    Private Partial Sub On用户名Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On用户名Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 手机() As Global.System.String
        Get
            Return _手机
        End Get
        Set
            On手机Changing(value)
            ReportPropertyChanging("手机")
            _手机 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("手机")
            On手机Changed()
        End Set
    End Property

    Private _手机 As Global.System.String
    Private Partial Sub On手机Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On手机Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 卡号() As Global.System.String
        Get
            Return _卡号
        End Get
        Set
            If (_卡号 <> Value) Then
                On卡号Changing(value)
                ReportPropertyChanging("卡号")
                _卡号 = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("卡号")
                On卡号Changed()
            End If
        End Set
    End Property

    Private _卡号 As Global.System.String
    Private Partial Sub On卡号Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On卡号Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 余额() As Global.System.Decimal
        Get
            Return _余额
        End Get
        Set
            If (_余额 <> Value) Then
                On余额Changing(value)
                ReportPropertyChanging("余额")
                _余额 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("余额")
                On余额Changed()
            End If
        End Set
    End Property

    Private _余额 As Global.System.Decimal
    Private Partial Sub On余额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On余额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 性别() As Global.System.String
        Get
            Return _性别
        End Get
        Set
            On性别Changing(value)
            ReportPropertyChanging("性别")
            _性别 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("性别")
            On性别Changed()
        End Set
    End Property

    Private _性别 As Global.System.String
    Private Partial Sub On性别Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On性别Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 激活时间() As Nullable(Of Global.System.DateTime)
        Get
            Return _激活时间
        End Get
        Set
            On激活时间Changing(value)
            ReportPropertyChanging("激活时间")
            _激活时间 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("激活时间")
            On激活时间Changed()
        End Set
    End Property

    Private _激活时间 As Nullable(Of Global.System.DateTime)
    Private Partial Sub On激活时间Changing(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub On激活时间Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 级别() As Global.System.String
        Get
            Return _级别
        End Get
        Set
            On级别Changing(value)
            ReportPropertyChanging("级别")
            _级别 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("级别")
            On级别Changed()
        End Set
    End Property

    Private _级别 As Global.System.String
    Private Partial Sub On级别Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On级别Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 年() As Nullable(Of Global.System.Int32)
        Get
            Return _年
        End Get
        Set
            On年Changing(value)
            ReportPropertyChanging("年")
            _年 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("年")
            On年Changed()
        End Set
    End Property

    Private _年 As Nullable(Of Global.System.Int32)
    Private Partial Sub On年Changing(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub On年Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 职业() As Global.System.String
        Get
            Return _职业
        End Get
        Set
            On职业Changing(value)
            ReportPropertyChanging("职业")
            _职业 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("职业")
            On职业Changed()
        End Set
    End Property

    Private _职业 As Global.System.String
    Private Partial Sub On职业Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On职业Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 消费额() As Global.System.Decimal
        Get
            Return _消费额
        End Get
        Set
            If (_消费额 <> Value) Then
                On消费额Changing(value)
                ReportPropertyChanging("消费额")
                _消费额 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("消费额")
                On消费额Changed()
            End If
        End Set
    End Property

    Private _消费额 As Global.System.Decimal
    Private Partial Sub On消费额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On消费额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 积分消费额() As Global.System.Decimal
        Get
            Return _积分消费额
        End Get
        Set
            If (_积分消费额 <> Value) Then
                On积分消费额Changing(value)
                ReportPropertyChanging("积分消费额")
                _积分消费额 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("积分消费额")
                On积分消费额Changed()
            End If
        End Set
    End Property

    Private _积分消费额 As Global.System.Decimal
    Private Partial Sub On积分消费额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On积分消费额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 现金消费额() As Global.System.Decimal
        Get
            Return _现金消费额
        End Get
        Set
            If (_现金消费额 <> Value) Then
                On现金消费额Changing(value)
                ReportPropertyChanging("现金消费额")
                _现金消费额 = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("现金消费额")
                On现金消费额Changed()
            End If
        End Set
    End Property

    Private _现金消费额 As Global.System.Decimal
    Private Partial Sub On现金消费额Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub On现金消费额Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property 发卡人() As Global.System.String
        Get
            Return _发卡人
        End Get
        Set
            On发卡人Changing(value)
            ReportPropertyChanging("发卡人")
            _发卡人 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("发卡人")
            On发卡人Changed()
        End Set
    End Property

    Private _发卡人 As Global.System.String
    Private Partial Sub On发卡人Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On发卡人Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property 状态() As Global.System.String
        Get
            Return _状态
        End Get
        Set
            If (_状态 <> Value) Then
                On状态Changing(value)
                ReportPropertyChanging("状态")
                _状态 = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("状态")
                On状态Changed()
            End If
        End Set
    End Property

    Private _状态 As Global.System.String
    Private Partial Sub On状态Changing(value As Global.System.String)
    End Sub

    Private Partial Sub On状态Changed()
    End Sub

    ''' <summary>
    ''' 没有元数据文档可用。
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property QQ() As Global.System.String
        Get
            Return _QQ
        End Get
        Set
            OnQQChanging(value)
            ReportPropertyChanging("QQ")
            _QQ = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("QQ")
            OnQQChanged()
        End Set
    End Property

    Private _QQ As Global.System.String
    Private Partial Sub OnQQChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnQQChanged()
    End Sub

    #End Region
End Class

#End Region

